# action.yml
name: 'Notion Cards'
description: "Update Notion cards' status based on events"
branding:
  icon: 'align-justify'  
  color: 'blue'
inputs:
  page_property: 
    description: 'The name of the property to update. Default is "Status"'
    required: false
    default: 'Status'
  on_pr:
    description: 'The value of page-property to be updated on PR event. Default is "Code Review"'
    required: false
    default: 'Code Review'
  on_merge:
    description: 'The value of page-property to be updated on PR MERGE event. Default is "QA Testing"'
    required: false
    default: 'QA Testing'
runs:
  using: 'docker'
  image: 'Dockerfile'
